### ISSUE TITLE
Add recovered cases, when possible

### ISSUE THREAD

**Issue by Matsuuu** [HS-Datadesk/koronavirus-avoindata#12]
It would be nice if we could collect data of recovered cases also. 

At least new york times has been able to collect this. https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html

Is it even possible to collect recovered cases in Finland? Or should we just start marking confirmed cases as cured after a set time?

@quarian

**Comment by quarian** [comment]
The recovered cases data has been tricky - I haven't found anywhere a reliable way to verify the recovered numbers (the New York times maps for example are based on the same global data we use for our global visualiations, which are based on [Johsn Hopkins data](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), and the recovered data from there seems to be entirely based on the [Chinese officials' data](https://ncov.dxy.cn/ncovh5/view/pneumonia?scene=2&clicktime=1579582238&enterid=1579582238&from=singlemessage&isappinstalled=0)). WHO for example doesn't report the recovered data in [their reports](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports). Nor does the [CDV](https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html).

If someone can provide a convincing argument for trusting that data we could integrate it fairly easily (though for Finland, there is only one reported recovery, which is the first case of the Chinese tourist and I'm unsure if that has been verified to have been recovered by other sources).

I'm not a virologist enough to say what time since case confirmation it would be safe to say someone is has recovered. It's true that if the disease doesn't kill you you'll get better, so some time trigger for this could work. Proposals for that kind of logic are accepted.

We'll discuss this internally, I'll get back on the topic. I'll go ahead and add the recovered list to our data for future proofing anyway today when I have time - for example if THL would announce that there has been a recovered case that could go there.

**Comment by quarian** [comment]
All right, I added the recovered field and updated the documentation. The work was done in [this PR](https://github.com/HS-Datadesk/koronavirus-avoindata/pull/14).

The content of the field is very much best effort at least at this point, since there is not yet an established channel for the recovered cases reporting. We figured that the Chinese information about the first case recovery is good enough, and since the case is old, added it to the recovered data. The other data point at this time is from [here](https://twitter.com/KantaHameenSHP/status/1237298451215454210?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1237298451215454210&ref_url=https%3A%2F%2Fwww.mtvuutiset.fi%2Fartikkeli%2Fkoronaviruksen-saanut-hameenlinnalaislapsi-parantunut-paasee-tanaan-pois-kotieristyksesta%2F7757106).

Keep on trucking, closing this issue now.

**Comment by Matsuuu** [comment]
Thanks !

I took a look at the data and it seems that in February, there was 2 recoveries, even though there was only one confirmed case. Is this intentional?

**Comment by quarian** [comment]
I typoed when entering data, the other case os from yesterday (so March). My bad! Fixed now. @Matsuuu

**Comment by Matsuuu** [comment]
Thank you !
