### ISSUE TITLE
Multiple types on field "infectionSource"

### ISSUE THREAD

**Issue by marcusziade** [HS-Datadesk/koronavirus-avoindata#33]
Please return one type from the infectionSource field.

You are referring to string IDs, but the returned data is Int.

**Comment by quarian** [comment]
Interesting, I'm pretty sure they used to be all strings at some point but the data sources might have changed that. Before I do anything I'll check the consumers listed on the page to see if they depend on the distinction - since the data is consistent in the way that it's either string `unknown`, `related to earlier` or a number. I'll do that when I have some time (it's pretty busy at the newsroom at this time) - or if multiple people arrive here complaining about the same thing. I don't want to break downstream consumers without notice.

**Comment by marcusziade** [comment]
Alright, thanks. It's just a huge inconvenience in type-safe languages like Swift 😬

I'd like to build an iOS app with this data
