### ISSUE TITLE
Results backdating: good or bad?

### ISSUE THREAD

**Issue by arobert3434** [HS-Datadesk/koronavirus-avoindata#66]
The results backdating used by THL has some logic to it, but makes the numbers difficult to interpret and compare with other countries. Basically one must take the last few days of data with a grain of salt until they are far enough in the past that the vast majority of test results have rolled in, which contradicts some of the whole idea of having a source of authoritative numbers. In some sense, leaving the recent days out of the derived data feed entirely might be something to consider (publishing only "confirmed" or "final" data). I don't know if I actually recommend this, but I just wanted to raise this issue that changing to THL-published data is not all positive.

**Comment by tnnmk** [comment]
I agree: While it is good to have also the current case counts based on testing date, case counts based on their publishing date would be useful too. Although it is possible to derive those latter counts by downloading the updated dataset every day and comparing its content to the one from previous day, the current situation is not ideal.

**Comment by quarian** [comment]
Day-to-day comparison with other countries is going to be tough anyway, since there is no guarantee that they report their data in the same manner (additionally, we don't necessarily know how much they have tested, do they maybe have a different criteria for positive tests, have they maybe changed those criteria at some point (this has happened), do they test all suspected cases etc). You should look more into the trends of the data rather than comparing the actual numbers - for example in Finland it's known that only the people in risk groups and in dire condition are tested (or this was the case at least for a while) whereas in South Korea they aggressively tested a huge number of cases. The Finnish confirmed numbers are in this light best at indicating the general spread rate of the virus and not necessarily the actual number of cases.

As for the case counts per day - when we did that, it was quite time consuming even when the health care districts would report their daily cases and now many of them don't report anything at all now that THL is reporting. I was considering when I migrated to this version of the API doing what was mentioned earlier and store the daily differences and continue reporting the daily increase. I decided against it because I couldn't think of a reasonable way to stitch together our old data and this new daily reporting data. Additionally, maintaining a stateless API (stateless in the sense that we only store the latest snapshots of data from THL for example) is easier than having to look after databases.

We are thinking about storing the daily snapshots of our data. If we decide to do that, introducing and API that would tell the daily reports would be possible - but in the meanwhile if you want something like that you should implement it yourself. It wouldn't bee too much work on top if this API.

**Comment by arobert3434** [comment]
Thanks, you make good points and the API being stateless certainly limits the options.
