### ISSUE TITLE
API palauttaa 502

### ISSUE THREAD

**Issue by Karvaporsas** [HS-Datadesk/koronavirus-avoindata#69]
Normaali api (https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaData/v2) palauttaa tällä hetkellä 502:sta.

**Comment by jingzhe** [comment]
Yesterday also had the same problem for a while.

**Comment by valstu** [comment]
@jingzhe Yesterdays problem was related to this https://github.com/HS-Datadesk/koronavirus-avoindata/issues/67

**Comment by quarian** [comment]
Let's see.

**Comment by quarian** [comment]
Right, it's up and running again. Sorry for the inconvenience - I haven't had the time for properly hardening the API. The root cause was the same as it was for https://github.com/HS-Datadesk/koronavirus-avoindata/issues/67 - the initial fix I made yesterday didn't fully properly address the updating data. If you agree that all is well, someone close the issue.

**Comment by haiksu** [comment]
Looks good to me.

**Comment by Karvaporsas** [comment]
Fixed
